name: Resume

on:
  workflow_dispatch:
    inputs:
      Name:
        required: true
      JOB:
        required: true
      DOB:
        required: true
      Email-id:
        required: true
      Work_experience:
        required: true
      Location:
        required: true
      Skills:
        required: true
      Gender:
        required: true
        type: choice
        options:
          - M
          - F
jobs:
  Resumee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  modify template
        run: |
            RESUME_FILE=./docs/${{github.event.inputs.Name}}.html
            cp index.html $RESUME_FILE
            ABOUTME=$(echo -e "Hi, this is ${{github.event.inputs.Name}} working as a ${{github.event.inputs.JOB}} holding an work experience of ${{github.event.inputs.Work_experience}}.\n Have proficient knowledge on skills such as ${{github.event.inputs.Skills}}.\n I am currently located at ${{github.event.inputs.Location}}.\n\nThanks for visiting my page!")
            if [[ "${{github.event.inputs.Gender}}" == "M" ]]; then
            sed -i "s+images+images/boy.jfif+g" $RESUME_FILE
            else
                sed -i "s+images+images/girl.jpg+g" $RESUME_FILE
            fi
            sed -i "s+USERNAME+${{github.event.inputs.Name}}+g" $RESUME_FILE
            sed -i "s+USERJOB+${{github.event.inputs.JOB}}+g" $RESUME_FILE
            sed -i "s+DATEOFBIRTH+${{github.event.inputs.DOB}}+g" $RESUME_FILE
            sed -i "s+EMAILID+${{github.event.inputs.Email-id}}+g" $RESUME_FILE
            sed -i "s+ABOUT+$ABOUTME+g" $RESUME_FILE
    
    
    
