name: Resume

on:
  workflow_dispatch:
    inputs:
      Name:
        required: true
      JOB:
        required: true
      DOB:
        required: true
      Email-id:
        required: true
      Gender:
        required: true
jobs:
  Resumee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check location
        run: pwd
      - name:  modify template
        run: |
            sed -i "s+USERNAME+${github.events.inputs.Name}+g" index.html
            sed -i "s+USERJOB+$J${github.events.inputs.JOB}+g" index.html
            sed -i "s+DATEOFBIRTH+${github.events.inputs.DOB}+g" index.html
            sed -i "s+EMAILID+${github.events.inputs.Email-id}+g" index.html
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
    
