name: Resume

on:
  workflow_dispatch:
    inputs:
      Name:
        required: true
      JOB:
        required: true
      DOB:
        required: true
      Email-id:
        required: true
      Gender:
        required: true
jobs:
  Resumee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check location
        run: pwd
      - name:  modify template
        run: bash setup.sh
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
    
