name: Resume

on:
  workflow_dispatch:
    inputs:
      Name:
        required: true
      JOB:
        required: true
      DOB:
        required: true
      Email-id:
        required: true
      Gender:
        required: true
