name: Resume

on:
  workflow_dispatch:
    inputs:
      Name:
        required: true
      JOB:
        required: true
      DOB:
        required: true
      Email-id:
        required: true
      Gender:
        required: true
jobs:
  Resumee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check location
        run: pwd
      - name:  modify template
        run: |
            sed -i "s+USERNAME+${{github.event.inputs.Name}}+g" index.html
            sed -i "s+USERJOB+$J${{github.event.inputs.JOB}}+g" index.html
            sed -i "s+DATEOFBIRTH+${{github.event.inputs.DOB}}+g" index.html
            sed -i "s+EMAILID+${{github.event.inputs.Email-id}}+g" index.html
            cat index.html
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
    
